-- MySQL Script generated by MySQL Workbench
-- 10/04/21 12:26:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pais` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `id_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ano` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ano` (
  `id_ano` INT NOT NULL,
  PRIMARY KEY (`id_ano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rel_pais_ano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rel_pais_ano` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rel_pais_ano` (
  `id_pais` VARCHAR(45) NOT NULL,
  `id_ano` INT NOT NULL,
  `rel_dado` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_pais`, `id_ano`),
  INDEX `id_ano_fk_idx` (`id_ano` ASC),
  CONSTRAINT `id_pais_fk`
    FOREIGN KEY (`id_pais`)
    REFERENCES `mydb`.`pais` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_ano_fk`
    FOREIGN KEY (`id_ano`)
    REFERENCES `mydb`.`ano` (`id_ano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
